const all = [
    ['Gibbering Mouther', 'monsters/16901-gibbering-mouther'],
    ['Nothic', 'monsters/17092-nothic'],
    ['Spectator', 'monsters/17094-spectator'],
    ['Chuul', 'monsters/16824-chuul'],
    ['Otyugh', 'monsters/16973-otyugh'],
    ['Cloaker', 'monsters/16826-cloaker'],
    ['Aboleth', 'monsters/16762-aboleth']
    ['Pegasus', 'monsters/16977-pegasus'],
    ['Couatl', 'monsters/16832-couatl'],
    ['Unicorn', 'monsters/17042-unicorn'],
    ['Deva', 'monsters/16840-deva'],
    ['Planetar', 'monsters/16980-planetar'],
    ['Solar', 'monsters/17016-solar']
    ['Homunculus', 'monsters/16926-homunculus'],
    ['Flying Sword', 'monsters/16865-flying-sword'],
    ['Animated Armor', 'monsters/16786-animated-armor'],
    ['Rug of Smothering', 'monsters/17000-rug-of-smothering'],
    ['Flesh Golem', 'monsters/16863-flesh-golem'],
    ['Shield Guardian', 'monsters/17012-shield-guardian'],
    ['Clay Golem', 'monsters/16825-clay-golem'],
    ['Stone Golem', 'monsters/17025-stone-golem'],
    ['Iron Golem', 'monsters/16935-iron-golem']
    ['Pseudodragon', 'monsters/16986-pseudodragon'],
    ['Wyvern', 'monsters/17065-wyvern'],
    ['Dragon Turtle', 'monsters/16845-dragon-turtle'],
    ['Brass Dragon Wyrmling', 'monsters/16814-brass-dragon-wyrmling'],
    ['Copper Dragon Wyrmling', 'monsters/16831-copper-dragon-wyrmling'],
    ['Black Dragon Wyrmling', 'monsters/16807-black-dragon-wyrmling'],
    ['Bronze Dragon Wyrmling', 'monsters/16815-bronze-dragon-wyrmling'],
    ['Green Dragon Wyrmling', 'monsters/16910-green-dragon-wyrmling'],
    ['Silver Dragon Wyrmling', 'monsters/17014-silver-dragon-wyrmling'],
    ['White Dragon Wyrmling', 'monsters/17058-white-dragon-wyrmling'],
    ['Blue Dragon Wyrmling', 'monsters/16811-blue-dragon-wyrmling'],
    ['Gold Dragon Wyrmling', 'monsters/17098-gold-dragon-wyrmling'],
    ['Red Dragon Wyrmling', 'monsters/16993-red-dragon-wyrmling'],
    ['Young Brass Dragon', 'monsters/17069-young-brass-dragon'],
    ['Young White Dragon', 'monsters/17076-young-white-dragon'],
    ['Young Black Dragon', 'monsters/17067-young-black-dragon'],
    ['Young Copper Dragon', 'monsters/17071-young-copper-dragon'],
    ['Young Bronze Dragon', 'monsters/17070-young-bronze-dragon'],
    ['Young Green Dragon', 'monsters/17073-young-green-dragon'],
    ['Young Blue Dragon', 'monsters/17068-young-blue-dragon'],
    ['Young Silver Dragon', 'monsters/17075-young-silver-dragon'],
    ['Young Gold Dragon', 'monsters/17072-young-gold-dragon'],
    ['Young Red Dragon', 'monsters/17074-young-red-dragon'],
    ['Adult Brass Dragon', 'monsters/16766-adult-brass-dragon'],
    ['Adult White Dragon', 'monsters/16773-adult-white-dragon'],
    ['Adult Black Dragon', 'monsters/16764-adult-black-dragon'],
    ['Adult Copper Dragon', 'monsters/16768-adult-copper-dragon'],
    ['Adult Bronze Dragon', 'monsters/16767-adult-bronze-dragon'],
    ['Adult Green Dragon', 'monsters/16770-adult-green-dragon'],
    ['Adult Blue Dragon', 'monsters/16765-adult-blue-dragon'],
    ['Adult Silver Dragon', 'monsters/16772-adult-silver-dragon'],
    ['Adult Gold Dragon', 'monsters/16769-adult-gold-dragon'],
    ['Adult Red Dragon', 'monsters/16771-adult-red-dragon'],
    ['Ancient Brass Dragon', 'https://www.dndbeyond.com/monsters/16777-ancient-brass-dragon'],
    ['Ancient White Dragon', 'https://www.dndbeyond.com/monsters/16784-ancient-white-dragon'],
    ['Ancient Black Dragon', 'https://www.dndbeyond.com/monsters/16775-ancient-black-dragon'],
    ['Ancient Copper Dragon', 'https://www.dndbeyond.com/monsters/16779-ancient-copper-dragon'],
    ['Ancient Bronze Dragon', 'https://www.dndbeyond.com/monsters/16778-ancient-bronze-dragon'],
    ['Ancient Green Dragon', 'https://www.dndbeyond.com/monsters/16781-ancient-green-dragon'],
    ['Ancient Blue Dragon', 'https://www.dndbeyond.com/monsters/16776-ancient-blue-dragon'],
    ['Ancient Silver Dragon', 'https://www.dndbeyond.com/monsters/16783-ancient-silver-dragon'],
    ['Ancient Gold Dragon', 'https://www.dndbeyond.com/monsters/16780-ancient-gold-dragon'],
    ['Ancient Red Dragon', 'https://www.dndbeyond.com/monsters/16782-ancient-red-dragon']
    ['Steam Mephit', 'monsters/17022-steam-mephit'],
    ['Dust Mephit', 'monsters/16851-dust-mephit'],
    ['Ice Mephit', 'monsters/16932-ice-mephit'],
    ['Magma Mephit', 'monsters/16948-magma-mephit'],
    ['Magmin', 'monsters/16949-magmin'],
    ['Azer', 'monsters/16794-azer'],
    ['Gargoyle', 'monsters/16868-gargoyle'],
    ['Air Elemental', 'monsters/16774-air-elemental'],
    ['Dust Devil', 'monsters/804867-dust-devil'],
    ['Earth Elemental', 'monsters/16853-earth-elemental'],
    ['Fire Elemental', 'monsters/16861-fire-elemental'],
    ['Salamander', 'monsters/17004-salamander'],
    ['Water Elemental', 'monsters/17051-water-elemental']
    ['Xorn', 'monsters/17066-xorn'],
    ['Invisible Stalker', 'monsters/16934-invisible-stalker'],
    ['Djinni', 'monsters/16842-djinni'],
    ['Efreeti', 'monsters/16854-efreeti']
    ['Blink Dog', 'monsters/16809-blink-dog'],
    ['Sprite', 'monsters/17020-sprite'],
    ['Satyr', 'monsters/17005-satyr'],
    ['Dryad', 'monsters/16849-dryad'],
    ['Sea Hag', 'monsters/17008-sea-hag'],
    ['Green Hag', 'monsters/16911-green-hag']
    ['Lemure', 'monsters/16942-lemure'],
    ['Dretch', 'monsters/16846-dretch'],
    ['Imp', 'monsters/16933-imp'],
    ['Quasit', 'monsters/16988-quasit'],
    ['Bearded Devil', 'monsters/16803-bearded-devil'],
    ['Hell Hound', 'monsters/16921-hell-hound'],
    ['Nightmare', 'monsters/16964-nightmare'],
    ['Incubus', 'monsters/257235-incubus'],
    ['Succubus', 'monsters/17027-succubus'],
    ['Barbed Devil', 'monsters/16800-barbed-devil'],
    ['Night Hag', 'monsters/16965-night-hag'],
    ['Vrock', 'monsters/17047-vrock'],
    ['Chain Devil', 'monsters/16822-chain-devil'],
    ['Hezrou', 'monsters/16922-hezrou'],
    ['Bone Devil', 'monsters/16813-bone-devil'],
    ['Glabrezu', 'monsters/16902-glabrezu'],
    ['Horned Devil', 'monsters/16927-horned-devil'],
    ['Erinyes', 'monsters/16858-erinyes'],
    ['Nalfeshnee', 'monsters/16963-nalfeshnee'],
    ['Rakshasa', 'monsters/16990-rakshasa'],
    ['Ice Devil', 'monsters/16931-ice-devil'],
    ['Marilith', 'monsters/16952-marilith'],
    ['Balor', 'monsters/16797-balor'],
    ['Pit Fiend', 'monsters/16979-pit-fiend']
    ['Ogre', 'monsters/16969-ogre'],
    ['Ettin', 'monsters/16860-ettin'],
    ['Hill Giant', 'monsters/16923-hill-giant'],
    ['Troll', 'monsters/17040-troll'],
    ['Cyclops', 'monsters/17090-cyclops'],
    ['Oni', 'monsters/16971-oni'],
    ['Stone Giant', 'monsters/17024-stone-giant'],
    ['Frost Giant', 'monsters/16867-frost-giant'],
    ['Cloud Giant', 'monsters/16827-cloud-giant'],
    ['Fire Giart', 'monsters/16862-fire-giant'],
    ['Storm Giant', 'monsters/17026-storm-giant']
    ['Bugbear', 'monsters/16817-bugbear'],
    ['Svirfneblin', 'monsters/17211-deep-gnome-svirfneblin'],
    ['Drow', 'monsters/17133-drow'],
    ['Duergar', 'monsters/16850-duergar'],
    ['Gnoll', 'monsters/16904-gnoll'],
    ['Goblin', 'monsters/16907-goblin'],
    ['Grimlock', 'monsters/16914-grimlock'],
    ['Half-Red Dragon Veteran', 'monsters/16918-half-red-dragon-veteran'],
    ['Hobgoblin', 'monsters/16925-hobgoblin'],
    ['Kobold', 'monsters/16939-kobold'],
    ['Lizardfolk', 'monsters/16946-lizardfolk'],
    ['Merfolk', 'monsters/16955-merfolk'],
    ['Orc', 'monsters/16972-orc'],
    ['Sahuagin', 'monsters/17003-sahuagin'],
    ['Werebear', 'monsters/17053-werebear'],
    ['Wereboar', 'monsters/17054-wereboar'],
    ['Wererat', 'monsters/17055-wererat'],
    ['Weretiger', 'monsters/17056-weretiger'],
    ['Werewolf', 'monsters/17057-werewolf']
    ['Cockatrice', 'monsters/16828-cockatrice'],
    ['Darkmantle', 'monsters/16837-darkmantle'],
    ['Rust Monster', 'monsters/17001-rust-monster'],
    ['Worg', 'monsters/17063-worg'],
    ['Death Dog', 'monsters/16838-death-dog'],
    ['Harpy', 'monsters/16919-harpy'],
    ['Hippogriff', 'monsters/16924-hippogriff'],
    ['Ankheg', 'monsters/16787-ankheg'],
    ['Centaur', 'monsters/16821-centaur'],
    ['Ettercap', 'monsters/16859-ettercap'],
    ['Grick', 'monsters/16912-grick'],
    ['Griffon', 'monsters/16913-griffon'],
    ['Merrow', 'monsters/16956-merrow'],
    ['Mimic', 'monsters/16957-mimic'],
    ['Basilisk', 'monsters/16801-basilisk'],
    ['Doppelganger', 'monsters/16843-doppelganger'],
    ['Manticore', 'monsters/16951-manticore'],
    ['Minotaur', 'monsters/16958-minotaur'],
    ['Owlbear', 'monsters/16975-owlbear'],
    ['Phase Spider', 'monsters/16978-phase-spider'],
    ['Winter Wolf', 'monsters/17061-winter-wolf'],
    ['Yeti', 'monsters/17096-yeti'],
    ['Lamia', 'monsters/16941-lamia'],
    ['Bulette', 'monsters/16818-bulette'],
    ['Gorgon', 'monsters/16908-gorgon'],
    ['Roper', 'monsters/16999-roper'],
    ['Chimera', 'monsters/16823-chimera'],
    ['Drider', 'monsters/16847-drider'],
    ['Medusa', 'monsters/16954-medusa'],
    ['Hydra', 'monsters/16929-hydra'],
    ['Spirit Naga', 'monsters/17019-spirit-naga'],
    ['Guardian Naga', 'monsters/16916-guardian-naga'],
    ['Behir', 'monsters/16804-behir'],
    ['Gynosphinx', 'monsters/16917-gynosphinx'],
    ['Remorhaz', 'monsters/16995-remorhaz'],
    ['Roc', 'monsters/16998-roc'],
    ['Purple Worm', 'monsters/16987-purple-worm'],
    ['Androsphinx', 'monsters/16785-androsphinx'],
    ['Kraken', 'monsters/16940-kraken'],
    ['Tarrasque', 'monsters/17034-tarrasque']
    ['Gray Ooze', 'monsters/16909-gray-ooze'],
    ['Gelatinous Cube', 'monsters/16869-gelatinous-cube'],
    ['Ochre Jelly', 'monsters/16967-ochre-jelly'],
    ['Black Pudding', 'monsters/16808-black-pudding']
    ['Awakened Shrub', 'monsters/16791-awakened-shrub'],
    ['Shrieker', 'monsters/17013-shrieker'],
    ['Twig Blight', 'monsters/17095-twig-blight'],
    ['Violet Fungus', 'monsters/17046-violet-fungus'],
    ['Awakened Tree', 'monsters/16792-awakened-tree'],
    ['Shambling Mound', 'monsters/17011-shambling-mound'],
    ['Treant', 'monsters/17037-treant']
    ['Skeleton', 'monsters/17015-skeleton'],
    ['Zombie', 'monsters/17077-zombie'],
    ['Shadow', 'monsters/17010-shadow'],
    ['Warhorse Skeleton', 'monsters/17050-warhorse-skeleton'],
    ['Ghoul', 'monsters/16872-ghoul'],
    ['Specter', 'monsters/17017-specter'],
    ['Ghast', 'monsters/16870-ghast'],
    ['Minotaur Skeleton', 'monsters/16959-minotaur-skeleton'],
    ['Ogre Zombie', 'monsters/16970-ogre-zombie'],
    [`Will-o'-Wisp`, 'monsters/17060-will-o-wisp'],
    ['Mummy', 'monsters/16961-mummy'],
    ['Wight', 'monsters/17059-wight'],
    ['Banshee', 'monsters/17089-banshee'],
    ['Flameskull', 'monsters/17091-flameskull'],
    ['Ghost', 'monsters/16871-ghost'],
    ['Vampire Spawn', 'monsters/17044-vampire-spawn'],
    ['Wraith', 'monsters/17064-wraith'],
    ['Vampire', 'monsters/17043-vampire'],
    ['Mummy Lord', 'monsters/16962-mummy-lord'],
    ['Lich', 'monsters/16943-lich']
];

const aberration = [
    ['Gibbering Mouther', 'monsters/16901-gibbering-mouther'],
    ['Nothic', 'monsters/17092-nothic'],
    ['Spectator', 'monsters/17094-spectator'],
    ['Chuul', 'monsters/16824-chuul'],
    ['Otyugh', 'monsters/16973-otyugh'],
    ['Cloaker', 'monsters/16826-cloaker'],
    ['Aboleth', 'monsters/16762-aboleth']
];

const celestial = [
    ['Pegasus', 'monsters/16977-pegasus'],
    ['Couatl', 'monsters/16832-couatl'],
    ['Unicorn', 'monsters/17042-unicorn'],
    ['Deva', 'monsters/16840-deva'],
    ['Planetar', 'monsters/16980-planetar'],
    ['Solar', 'monsters/17016-solar']
];

const construct = [
    ['Homunculus', 'monsters/16926-homunculus'],
    ['Flying Sword', 'monsters/16865-flying-sword'],
    ['Animated Armor', 'monsters/16786-animated-armor'],
    ['Rug of Smothering', 'monsters/17000-rug-of-smothering'],
    ['Flesh Golem', 'monsters/16863-flesh-golem'],
    ['Shield Guardian', 'monsters/17012-shield-guardian'],
    ['Clay Golem', 'monsters/16825-clay-golem'],
    ['Stone Golem', 'monsters/17025-stone-golem'],
    ['Iron Golem', 'monsters/16935-iron-golem']
];

const dragon = [
    ['Pseudodragon', 'monsters/16986-pseudodragon'],
    ['Wyvern', 'monsters/17065-wyvern'],
    ['Dragon Turtle', 'monsters/16845-dragon-turtle'],
    ['Brass Dragon Wyrmling', 'monsters/16814-brass-dragon-wyrmling'],
    ['Copper Dragon Wyrmling', 'monsters/16831-copper-dragon-wyrmling'],
    ['Black Dragon Wyrmling', 'monsters/16807-black-dragon-wyrmling'],
    ['Bronze Dragon Wyrmling', 'monsters/16815-bronze-dragon-wyrmling'],
    ['Green Dragon Wyrmling', 'monsters/16910-green-dragon-wyrmling'],
    ['Silver Dragon Wyrmling', 'monsters/17014-silver-dragon-wyrmling'],
    ['White Dragon Wyrmling', 'monsters/17058-white-dragon-wyrmling'],
    ['Blue Dragon Wyrmling', 'monsters/16811-blue-dragon-wyrmling'],
    ['Gold Dragon Wyrmling', 'monsters/17098-gold-dragon-wyrmling'],
    ['Red Dragon Wyrmling', 'monsters/16993-red-dragon-wyrmling'],
    ['Young Brass Dragon', 'monsters/17069-young-brass-dragon'],
    ['Young White Dragon', 'monsters/17076-young-white-dragon'],
    ['Young Black Dragon', 'monsters/17067-young-black-dragon'],
    ['Young Copper Dragon', 'monsters/17071-young-copper-dragon'],
    ['Young Bronze Dragon', 'monsters/17070-young-bronze-dragon'],
    ['Young Green Dragon', 'monsters/17073-young-green-dragon'],
    ['Young Blue Dragon', 'monsters/17068-young-blue-dragon'],
    ['Young Silver Dragon', 'monsters/17075-young-silver-dragon'],
    ['Young Gold Dragon', 'monsters/17072-young-gold-dragon'],
    ['Young Red Dragon', 'monsters/17074-young-red-dragon'],
    ['Adult Brass Dragon', 'monsters/16766-adult-brass-dragon'],
    ['Adult White Dragon', 'monsters/16773-adult-white-dragon'],
    ['Adult Black Dragon', 'monsters/16764-adult-black-dragon'],
    ['Adult Copper Dragon', 'monsters/16768-adult-copper-dragon'],
    ['Adult Bronze Dragon', 'monsters/16767-adult-bronze-dragon'],
    ['Adult Green Dragon', 'monsters/16770-adult-green-dragon'],
    ['Adult Blue Dragon', 'monsters/16765-adult-blue-dragon'],
    ['Adult Silver Dragon', 'monsters/16772-adult-silver-dragon'],
    ['Adult Gold Dragon', 'monsters/16769-adult-gold-dragon'],
    ['Adult Red Dragon', 'monsters/16771-adult-red-dragon'],
    ['Ancient Brass Dragon', 'monsters/16777-ancient-brass-dragon'],
    ['Ancient White Dragon', 'monsters/16784-ancient-white-dragon'],
    ['Ancient Black Dragon', 'monsters/16775-ancient-black-dragon'],
    ['Ancient Copper Dragon', 'monsters/16779-ancient-copper-dragon'],
    ['Ancient Bronze Dragon', 'monsters/16778-ancient-bronze-dragon'],
    ['Ancient Green Dragon', 'monsters/16781-ancient-green-dragon'],
    ['Ancient Blue Dragon', 'monsters/16776-ancient-blue-dragon'],
    ['Ancient Silver Dragon', 'monsters/16783-ancient-silver-dragon'],
    ['Ancient Gold Dragon', 'monsters/16780-ancient-gold-dragon'],
    ['Ancient Red Dragon', 'monsters/16782-ancient-red-dragon']
];

const dragonWyrmling = [
    ['Brass Dragon Wyrmling', 'monsters/16814-brass-dragon-wyrmling'],
    ['Copper Dragon Wyrmling', 'monsters/16831-copper-dragon-wyrmling'],
    ['Black Dragon Wyrmling', 'monsters/16807-black-dragon-wyrmling'],
    ['Bronze Dragon Wyrmling', 'monsters/16815-bronze-dragon-wyrmling'],
    ['Green Dragon Wyrmling', 'monsters/16910-green-dragon-wyrmling'],
    ['Silver Dragon Wyrmling', 'monsters/17014-silver-dragon-wyrmling'],
    ['White Dragon Wyrmling', 'monsters/17058-white-dragon-wyrmling'],
    ['Blue Dragon Wyrmling', 'monsters/16811-blue-dragon-wyrmling'],
    ['Gold Dragon Wyrmling', 'monsters/17098-gold-dragon-wyrmling'],
    ['Red Dragon Wyrmling', 'monsters/16993-red-dragon-wyrmling']
];

const dragonYoung = [
    ['Young Brass Dragon', 'monsters/17069-young-brass-dragon'],
    ['Young White Dragon', 'monsters/17076-young-white-dragon'],
    ['Young Black Dragon', 'monsters/17067-young-black-dragon'],
    ['Young Copper Dragon', 'monsters/17071-young-copper-dragon'],
    ['Young Bronze Dragon', 'monsters/17070-young-bronze-dragon'],
    ['Young Green Dragon', 'monsters/17073-young-green-dragon'],
    ['Young Blue Dragon', 'monsters/17068-young-blue-dragon'],
    ['Young Silver Dragon', 'monsters/17075-young-silver-dragon'],
    ['Young Gold Dragon', 'monsters/17072-young-gold-dragon'],
    ['Young Red Dragon', 'monsters/17074-young-red-dragon']
];

const dragonAdult = [
    ['Adult Brass Dragon', 'monsters/16766-adult-brass-dragon'],
    ['Adult White Dragon', 'monsters/16773-adult-white-dragon'],
    ['Adult Black Dragon', 'monsters/16764-adult-black-dragon'],
    ['Adult Copper Dragon', 'monsters/16768-adult-copper-dragon'],
    ['Adult Bronze Dragon', 'monsters/16767-adult-bronze-dragon'],
    ['Adult Green Dragon', 'monsters/16770-adult-green-dragon'],
    ['Adult Blue Dragon', 'monsters/16765-adult-blue-dragon'],
    ['Adult Silver Dragon', 'monsters/16772-adult-silver-dragon'],
    ['Adult Gold Dragon', 'monsters/16769-adult-gold-dragon'],
    ['Adult Red Dragon', 'monsters/16771-adult-red-dragon']
];

const dragonAncient = [
    ['Ancient Brass Dragon', 'monsters/16777-ancient-brass-dragon'],
    ['Ancient White Dragon', 'monsters/16784-ancient-white-dragon'],
    ['Ancient Black Dragon', 'monsters/16775-ancient-black-dragon'],
    ['Ancient Copper Dragon', 'monsters/16779-ancient-copper-dragon'],
    ['Ancient Bronze Dragon', 'monsters/16778-ancient-bronze-dragon'],
    ['Ancient Green Dragon', 'monsters/16781-ancient-green-dragon'],
    ['Ancient Blue Dragon', 'monsters/16776-ancient-blue-dragon'],
    ['Ancient Silver Dragon', 'monsters/16783-ancient-silver-dragon'],
    ['Ancient Gold Dragon', 'monsters/16780-ancient-gold-dragon'],
    ['Ancient Red Dragon', 'monsters/16782-ancient-red-dragon']
];

const elemental = [
    ['Steam Mephit', 'monsters/17022-steam-mephit'],
    ['Dust Mephit', 'monsters/16851-dust-mephit'],
    ['Ice Mephit', 'monsters/16932-ice-mephit'],
    ['Magma Mephit', 'monsters/16948-magma-mephit'],
    ['Magmin', 'monsters/16949-magmin'],
    ['Azer', 'monsters/16794-azer'],
    ['Gargoyle', 'monsters/16868-gargoyle'],
    ['Air Elemental', 'monsters/16774-air-elemental'],
    ['Dust Devil', 'monsters/804867-dust-devil'],
    ['Earth Elemental', 'monsters/16853-earth-elemental'],
    ['Fire Elemental', 'monsters/16861-fire-elemental'],
    ['Salamander', 'monsters/17004-salamander'],
    ['Water Elemental', 'monsters/17051-water-elemental']
    ['Xorn', 'monsters/17066-xorn'],
    ['Invisible Stalker', 'monsters/16934-invisible-stalker'],
    ['Djinni', 'monsters/16842-djinni'],
    ['Efreeti', 'monsters/16854-efreeti']
];

const fey = [
    ['Blink Dog', 'monsters/16809-blink-dog'],
    ['Sprite', 'monsters/17020-sprite'],
    ['Satyr', 'monsters/17005-satyr'],
    ['Dryad', 'monsters/16849-dryad'],
    ['Sea Hag', 'monsters/17008-sea-hag'],
    ['Green Hag', 'monsters/16911-green-hag']
];

const fiend = [
    ['Lemure', 'monsters/16942-lemure'],
    ['Dretch', 'monsters/16846-dretch'],
    ['Imp', 'monsters/16933-imp'],
    ['Quasit', 'monsters/16988-quasit'],
    ['Bearded Devil', 'monsters/16803-bearded-devil'],
    ['Hell Hound', 'monsters/16921-hell-hound'],
    ['Nightmare', 'monsters/16964-nightmare'],
    ['Incubus', 'monsters/257235-incubus'],
    ['Succubus', 'monsters/17027-succubus'],
    ['Barbed Devil', 'monsters/16800-barbed-devil'],
    ['Night Hag', 'monsters/16965-night-hag'],
    ['Vrock', 'monsters/17047-vrock'],
    ['Chain Devil', 'monsters/16822-chain-devil'],
    ['Hezrou', 'monsters/16922-hezrou'],
    ['Bone Devil', 'monsters/16813-bone-devil'],
    ['Glabrezu', 'monsters/16902-glabrezu'],
    ['Horned Devil', 'monsters/16927-horned-devil'],
    ['Erinyes', 'monsters/16858-erinyes'],
    ['Nalfeshnee', 'monsters/16963-nalfeshnee'],
    ['Rakshasa', 'monsters/16990-rakshasa'],
    ['Ice Devil', 'monsters/16931-ice-devil'],
    ['Marilith', 'monsters/16952-marilith'],
    ['Balor', 'monsters/16797-balor'],
    ['Pit Fiend', 'monsters/16979-pit-fiend']
];

const giant = [
    ['Ogre', 'monsters/16969-ogre'],
    ['Ettin', 'monsters/16860-ettin'],
    ['Hill Giant', 'monsters/16923-hill-giant'],
    ['Troll', 'monsters/17040-troll'],
    ['Cyclops', 'monsters/17090-cyclops'],
    ['Oni', 'monsters/16971-oni'],
    ['Stone Giant', 'monsters/17024-stone-giant'],
    ['Frost Giant', 'monsters/16867-frost-giant'],
    ['Cloud Giant', 'monsters/16827-cloud-giant'],
    ['Fire Giart', 'monsters/16862-fire-giant'],
    ['Storm Giant', 'monsters/17026-storm-giant']
];

const humanoid = [
    ['Bugbear', 'monsters/16817-bugbear'],
    ['Svirfneblin', 'monsters/17211-deep-gnome-svirfneblin'],
    ['Drow', 'monsters/17133-drow'],
    ['Duergar', 'monsters/16850-duergar'],
    ['Gnoll', 'monsters/16904-gnoll'],
    ['Goblin', 'monsters/16907-goblin'],
    ['Grimlock', 'monsters/16914-grimlock'],
    ['Half-Red Dragon Veteran', 'monsters/16918-half-red-dragon-veteran'],
    ['Hobgoblin', 'monsters/16925-hobgoblin'],
    ['Kobold', 'monsters/16939-kobold'],
    ['Lizardfolk', 'monsters/16946-lizardfolk'],
    ['Merfolk', 'monsters/16955-merfolk'],
    ['Orc', 'monsters/16972-orc'],
    ['Sahuagin', 'monsters/17003-sahuagin'],
    ['Werebear', 'monsters/17053-werebear'],
    ['Wereboar', 'monsters/17054-wereboar'],
    ['Wererat', 'monsters/17055-wererat'],
    ['Weretiger', 'monsters/17056-weretiger'],
    ['Werewolf', 'monsters/17057-werewolf']
];

const monstrosity = [
    ['Cockatrice', 'monsters/16828-cockatrice'],
    ['Darkmantle', 'monsters/16837-darkmantle'],
    ['Rust Monster', 'monsters/17001-rust-monster'],
    ['Worg', 'monsters/17063-worg'],
    ['Death Dog', 'monsters/16838-death-dog'],
    ['Harpy', 'monsters/16919-harpy'],
    ['Hippogriff', 'monsters/16924-hippogriff'],
    ['Ankheg', 'monsters/16787-ankheg'],
    ['Centaur', 'monsters/16821-centaur'],
    ['Ettercap', 'monsters/16859-ettercap'],
    ['Grick', 'monsters/16912-grick'],
    ['Griffon', 'monsters/16913-griffon'],
    ['Merrow', 'monsters/16956-merrow'],
    ['Mimic', 'monsters/16957-mimic'],
    ['Basilisk', 'monsters/16801-basilisk'],
    ['Doppelganger', 'monsters/16843-doppelganger'],
    ['Manticore', 'monsters/16951-manticore'],
    ['Minotaur', 'monsters/16958-minotaur'],
    ['Owlbear', 'monsters/16975-owlbear'],
    ['Phase Spider', 'monsters/16978-phase-spider'],
    ['Winter Wolf', 'monsters/17061-winter-wolf'],
    ['Yeti', 'monsters/17096-yeti'],
    ['Lamia', 'monsters/16941-lamia'],
    ['Bulette', 'monsters/16818-bulette'],
    ['Gorgon', 'monsters/16908-gorgon'],
    ['Roper', 'monsters/16999-roper'],
    ['Chimera', 'monsters/16823-chimera'],
    ['Drider', 'monsters/16847-drider'],
    ['Medusa', 'monsters/16954-medusa'],
    ['Hydra', 'monsters/16929-hydra'],
    ['Spirit Naga', 'monsters/17019-spirit-naga'],
    ['Guardian Naga', 'monsters/16916-guardian-naga'],
    ['Behir', 'monsters/16804-behir'],
    ['Gynosphinx', 'monsters/16917-gynosphinx'],
    ['Remorhaz', 'monsters/16995-remorhaz'],
    ['Roc', 'monsters/16998-roc'],
    ['Purple Worm', 'monsters/16987-purple-worm'],
    ['Androsphinx', 'monsters/16785-androsphinx'],
    ['Kraken', 'monsters/16940-kraken'],
    ['Tarrasque', 'monsters/17034-tarrasque']
];

const ooze = [
    ['Gray Ooze', 'monsters/16909-gray-ooze'],
    ['Gelatinous Cube', 'monsters/16869-gelatinous-cube'],
    ['Ochre Jelly', 'monsters/16967-ochre-jelly'],
    ['Black Pudding', 'monsters/16808-black-pudding']
];

const plant = [
    ['Awakened Shrub', 'monsters/16791-awakened-shrub'],
    ['Shrieker', 'monsters/17013-shrieker'],
    ['Twig Blight', 'monsters/17095-twig-blight'],
    ['Violet Fungus', 'monsters/17046-violet-fungus'],
    ['Awakened Tree', 'monsters/16792-awakened-tree'],
    ['Shambling Mound', 'monsters/17011-shambling-mound'],
    ['Treant', 'monsters/17037-treant']
];

const undead = [
    ['Skeleton', 'monsters/17015-skeleton'],
    ['Zombie', 'monsters/17077-zombie'],
    ['Shadow', 'monsters/17010-shadow'],
    ['Warhorse Skeleton', 'monsters/17050-warhorse-skeleton'],
    ['Ghoul', 'monsters/16872-ghoul'],
    ['Specter', 'monsters/17017-specter'],
    ['Ghast', 'monsters/16870-ghast'],
    ['Minotaur Skeleton', 'monsters/16959-minotaur-skeleton'],
    ['Ogre Zombie', 'monsters/16970-ogre-zombie'],
    [`Will-o'-Wisp`, 'monsters/17060-will-o-wisp'],
    ['Mummy', 'monsters/16961-mummy'],
    ['Wight', 'monsters/17059-wight'],
    ['Banshee', 'monsters/17089-banshee'],
    ['Flameskull', 'monsters/17091-flameskull'],
    ['Ghost', 'monsters/16871-ghost'],
    ['Vampire Spawn', 'monsters/17044-vampire-spawn'],
    ['Wraith', 'monsters/17064-wraith'],
    ['Vampire', 'monsters/17043-vampire'],
    ['Mummy Lord', 'monsters/16962-mummy-lord'],
    ['Lich', 'monsters/16943-lich']
];