const cantrips = [
    '<em><a href="https://www.dndbeyond.com/spells/1989-acid-splash" target="_blank">Acid Splash</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2026-chill-touch" target="_blank">Chill Touch</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2057-dancing-lights" target="_blank">Dancing Lights</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2103-fire-bolt" target="_blank">Fire Bolt</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2166-light" target="_blank">Light</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2173-mage-hand" target="_blank">Mage Hand</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2187-mending" target="_blank">Mending</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2188-message" target="_blank">Message</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2191-minor-illusion" target="_blank">Minor Illusion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2208-poison-spray" target="_blank">Poison Spray</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2213-prestidigitation" target="_blank">Prestidigitation</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2226-ray-of-frost" target="_blank">Ray of Frost</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2250-shocking-grasp" target="_blank">Shocking Grasp</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2287-true-strike" target="_blank">True Strike</a></em>'
];

const spells1st = [
    '<em><a href="https://www.dndbeyond.com/spells/1991-alarm" target="_blank">Alarm</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2021-burning-hands" target="_blank">Burning Hands</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2025-charm-person" target="_blank">Charm Person</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2031-color-spray" target="_blank">Color Spray</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2035-comprehend-languages" target="_blank">Comprehend Languages</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2065-detect-magic" target="_blank">Detect Magic</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2069-disguise-self" target="_blank">Disguise Self</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2088-expeditious-retreat" target="_blank">Expedious Retreat</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2093-false-life" target="_blank">False Life</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2095-feather-fall" target="_blank">Feather Fall</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2097-find-familiar" target="_blank">Find Familiar</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2110-floating-disk" target="_blank">Floating Disk</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2112-fog-cloud" target="_blank">Fog Cloud</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2127-grease" target="_blank">Grease</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2145-hideous-laughter" target="_blank">Hideous Laughter</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2152-identify" target="_blank">Identify</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2153-illusory-script" target="_blank">Illusory Script</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2161-jump" target="_blank">Jump</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2171-longstrider" target="_blank">Longstrider</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2172-mage-armor" target="_blank">Mage Armor</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2176-magic-missile" target="_blank">Magic Missile</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2221-protection-from-evil-and-good" target="_blank">Protection from Evil and Good</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2247-shield" target="_blank">Shield</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2252-silent-image" target="_blank">Silent Image</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2254-sleep" target="_blank">Sleep</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2278-thunderwave" target="_blank">Thunderwave</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2288-unseen-servant" target="_blank">Unseen Servant</a></em>'
];

const spells2nd = [
    '<em><a href="https://www.dndbeyond.com/spells/1988-acid-arrow" target="_blank">Acid Arrow</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/1992-alter-self" target="_blank">Alter Self</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2003-arcane-lock" target="_blank">Arcane Lock</a></em>',
    `<em><a href="https://www.dndbeyond.com/spells/2005-arcanists-magic-aura" target="_blank">Arcanist's Magic Aura</a></em>`,
    '<em><a href="https://www.dndbeyond.com/spells/2018-blindness-deafness" target="_blank">Blindness/Deafness</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2020-blur" target="_blank">Blur</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2048-continual-flame" target="_blank">Continual Flame</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2058-darkness" target="_blank">Darkness</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2059-darkvision" target="_blank">Darkvision</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2067-detect-thoughts" target="_blank">Detect Thoughts</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2084-enlarge-reduce" target="_blank">Enlarge/Reduce</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2108-flaming-sphere" target="_blank">Flaming Sphere</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2121-gentle-repose" target="_blank">Gentle Repose</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2134-gust-of-wind" target="_blank">Gust of Wind</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2147-hold-person" target="_blank">Hold Person</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2159-invisibility" target="_blank">Invisibility</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2162-knock" target="_blank">Knock</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2165-levitate" target="_blank">Levitate</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2170-locate-object" target="_blank">Locate Object</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2177-magic-mouth" target="_blank">Magic Mouth</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2178-magic-weapon" target="_blank">Magic Weapon</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2193-mirror-image" target="_blank">Mirror Image</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2195-misty-step" target="_blank">Misty Step</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2225-ray-of-enfeeblement" target="_blank">Ray of Enfeeblement</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2235-rope-trick" target="_blank">Rope Trick</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2238-scorching-ray" target="_blank">Scorching Ray</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2242-see-invisibility" target="_blank">See Invisibility</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2246-shatter" target="_blank">Shatter</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2261-spider-climb" target="_blank">Spider Climb</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2269-suggestion" target="_blank">Suggestion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2299-web" target="_blank">Web</a></em>'
];

const spells3rd = [
    '<em><a href="https://www.dndbeyond.com/spells/1996-animate-dead" target="_blank">Animate Dead</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2013-bestow-curse" target="_blank">Bestow Curse</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2019-blink" target="_blank">Blink</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2028-clairvoyance" target="_blank">Clairvoyance</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2051-counterspell" target="_blank">Counterspell</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2072-dispel-magic" target="_blank">Dispell Magic</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2094-fear" target="_blank">Fear</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2102-fireball" target="_blank">Fireball</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2111-fly" target="_blank">Fly</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2118-gaseous-form" target="_blank">Gaseous Form</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2125-glyph-of-warding" target="_blank">Glyph of Warding</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2138-haste" target="_blank">Haste</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2150-hypnotic-pattern" target="_blank">Hypnotic Pattern</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2167-lightning-bolt" target="_blank">Lightning Bolt</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2174-magic-circle" target="_blank">Magic Circle</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2180-major-image" target="_blank">Major Image</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2199-nondetection" target="_blank">Nondetection</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2203-phantom-steed" target="_blank">Phantom Steed</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2220-protection-from-energy" target="_blank">Protection from Energy</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2229-remove-curse" target="_blank">Remove Curse</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2243-sending" target="_blank">Sending</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2255-sleet-storm" target="_blank">Sleet Storm</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2256-slow" target="_blank">Slow</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2265-stinking-cloud" target="_blank">Stinking Cloud</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2280-tiny-hut" target="_blank">Tiny Hut</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2281-tongues" target="_blank">Tongues</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2289-vampiric-touch" target="_blank">Vampiric Touch</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2297-water-breathing" target="_blank">Water Breathing</a></em>'
];

const spells4th = [
    '<em><a href="https://www.dndbeyond.com/spells/2001-arcane-eye" target="_blank">Arcane Eye</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2010-banishment" target="_blank">Banishment</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2014-black-tentacles" target="_blank">Black Tentacles</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2017-blight" target="_blank">Blight</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2038-confusion" target="_blank">Confusion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2043-conjure-minor-elementals" target="_blank">Conjur Minor Elemental</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2049-control-water" target="_blank">Control Water</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2068-dimension-door" target="_blank">Dimension Door</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2090-fabricate" target="_blank">Fabricate</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2092-faithful-hound" target="_blank">Faithful Hound</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2104-fire-shield" target="_blank">Fire Shield</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2128-greater-invisibility" target="_blank">Greater Invisibility</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2136-hallucinatory-terrain" target="_blank">Hallucinatory Terrain</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2151-ice-storm" target="_blank">Ice Storm</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2169-locate-creature" target="_blank">Locate Creature</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2202-phantasmal-killer" target="_blank">Phantasmal Killer</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2209-polymorph" target="_blank">Polymorph</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2216-private-sanctum" target="_blank">Private Sanctum</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2230-resilient-sphere" target="_blank">Resilient Sphere</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2240-secret-chest" target="_blank">Secret Chest</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2267-stone-shape" target="_blank">Stone Shape</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2266-stoneskin" target="_blank">Stoneskin</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2291-wall-of-fire" target="_blank">Wall of Fire</a></em>'
];

const spells5th = [
    '<em><a href="https://www.dndbeyond.com/spells/1997-animate-objects" target="_blank">Animate Objects</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2002-arcane-hand" target="_blank">Arcane Hand</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2030-cloudkill" target="_blank">Cloudkill</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2037-cone-of-cold" target="_blank">Cone of Cold</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2041-conjure-elemental" target="_blank">Conjur Elemental</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2045-contact-other-plane" target="_blank">Contact Other Plane</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2055-creation" target="_blank">Creation</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2078-dominate-person" target="_blank">Dominate Person</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2079-dream" target="_blank">Dream</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2120-geas" target="_blank">Geas</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2146-hold-monster" target="_blank">Hold Monster</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2163-legend-lore" target="_blank">Legend Lore</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2194-mislead" target="_blank">Mislead</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2196-modify-memory" target="_blank">Modify Memory</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2200-passwall" target="_blank">Passwell</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2205-planar-binding" target="_blank">Planar Building</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2239-scrying" target="_blank">Scrying</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2241-seeming" target="_blank">Seeming</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2273-telekinesis" target="_blank">Telekinesis</a></em>',
    '<em><a href=https://www.dndbeyond.com/spells/2274-telepathic-bond" target="_blank">Telepathic Bond</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2276-teleportation-circle" target="_blank">Teleportation Circle</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2292-wall-of-force" target="_blank">Wall of Force</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2294-wall-of-stone" target="_blank">Wall of Stone</a></em>'
];

const spells6th = [
    '<em><a href="https://www.dndbeyond.com/spells/2024-chain-lightning" target="_blank">Chain Lightning</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2027-circle-of-death" target="_blank">Circle of Death</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2047-contingency" target="_blank">Contingency</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2054-create-undead" target="_blank">Create Undead</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2070-disintegrate" target="_blank">Disintegrate</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2089-eyebite" target="_blank">Eyebite</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2109-flesh-to-stone" target="_blank">Flesh to Stone</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2117-freezing-sphere" target="_blank">Freezing Sphere</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2124-globe-of-invulnerability" target="_blank">Globe of Invulnerability</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2131-guards-and-wards" target="_blank">Guards and Wands</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2158-instant-summons" target="_blank">Instant Summons</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2175-magic-jar" target="_blank">Magic Jar</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2184-mass-suggestion" target="_blank">Mass Suggestion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2198-move-earth" target="_blank">Move Earth</a></em>',
    `<em><a href="https://www.dndbeyond.com/spells/2160-ottos-irresistible-dance" target="_blank">Otto's Irresistible Dance</a></em>`,
    '<em><a href="https://www.dndbeyond.com/spells/2218-programmed-illusion" target="_blank">Programmed Illusion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2270-sunbeam" target="_blank">Sunbeam</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2286-true-seeing" target="_blank">True Seeing</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2293-wall-of-ice" target="_blank">Wall of Ice</a></em>'
];

const spells7th = [
    '<em><a href="https://www.dndbeyond.com/spells/2062-delayed-blast-fireball" target="_blank">Delayed Blast Fireball</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2087-etherealness" target="_blank">Etherealness</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2101-finger-of-death" target="_blank">Finger of Death</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2114-forcecage" target="_blank">Forcecage</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2179-magnificent-mansion" target="_blank">Magnificent Mansion</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2192-mirage-arcane" target="_blank">Mirage Arcane</a></em>',
    `<em><a href="https://www.dndbeyond.com/spells/2004-mordenkainens-sword" target="_blank">Mordenkainen's Sword</a></em>`,
    '<em><a href="https://www.dndbeyond.com/spells/2206-plane-shift" target="_blank">Plane Shift</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2214-prismatic-spray" target="_blank">Prismatic Spray</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2219-project-image" target="_blank">Project Image</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2233-reverse-gravity" target="_blank">Reverse Gravity</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2244-sequester" target="_blank">Sequester</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2253-simulacrum" target="_blank">Simulacrum</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2272-symbol" target="_blank">Symbol</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2275-teleport" target="_blank">Teleport</a></em>'
];

const spells8th = [
    '<em><a href="https://www.dndbeyond.com/spells/1999-antimagic-field" target="_blank">Antimagic Field</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2000-antipathy-sympathy" target="_blank">Antipathy/Sympathy</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2029-clone" target="_blank">Clone</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2050-control-weather" target="_blank">Control Weather</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2063-demiplane" target="_blank">Demiplane</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2077-dominate-monster" target="_blank">Dominate Monster</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2096-feeblemind" target="_blank">Feeblemind</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2155-incendiary-cloud" target="_blank">Incendiary Cloud</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2185-maze" target="_blank">Maze</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2190-mind-blank" target="_blank">Mind Blank</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2211-power-word-stun" target="_blank">Power Word Stun</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2271-sunburst" target="_blank">Sunburst</a></em>'
];

const spells9th = [
    '<em><a href="https://www.dndbeyond.com/spells/2006-astral-projection" target="_blank">Astral Projection</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2115-foresight" target="_blank">Foresight</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2119-gate" target="_blank">Gate</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2154-imprisonment" target="_blank">Imprisonment</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2189-meteor-swarm" target="_blank">Meteor Swarm</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2210-power-word-kill" target="_blank">Power Word Kill</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2215-prismatic-wall" target="_blank">Prismatic Wall</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2245-shapechange" target="_blank">Shapechange</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2279-time-stop" target="_blank">Time Stop</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2284-true-polymorph" target="_blank">True Polymorph</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2300-weird" target="_blank">Weird</a></em>',
    '<em><a href="https://www.dndbeyond.com/spells/2303-wish" target="_blank">Wish</a></em>'
];